version: '3'
services:
  mysql:
    container_name: todo
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: todo-repository
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    restart: always